Update artemis version
BeshoyMelika/mmd-ecommerce-fl-lib pull request #19
Opened 2020-09-21 17:11 UTC by BeshoyMelika

2020-09-22 13:04 UTC, MinaSamirCap requested changes

2020-09-22 13:04 UTC, MinaSamirCap commented on example/lib/APIs.dart
> +  GeneralApiManager.brandsApi((List<Brands$Query$Brand> brands) {}, () {});
find a mapping way to map the names

2020-09-22 13:04 UTC, MinaSamirCap commented on pubspec.yaml
> +  artemis: ^6.12.3-beta.1
add comments above the library

2020-09-22 13:04 UTC, MinaSamirCap commented on pubspec.yaml
>    path_provider: ^1.5.1
show me the exception of path_provider package

2020-09-22 13:04 UTC, MinaSamirCap commented on lib/common_models/common_models.dart
> +// import 'package:mmd_ecommerce_fl_lib/generatedql/auth/graphql_api.dart' as A;
if you did not find a map way you will write by your self ..

2020-09-24 10:44 UTC, BeshoyMelika commented on pubspec.yaml
>    path_provider: ^1.5.1
fixed after update path_provider 1.6.18

2020-09-24 12:23 UTC, BeshoyMelika commented on example/lib/APIs.dart
> +  GeneralApiManager.brandsApi((List<Brands$Query$Brand> brands) {}, () {});
i open a new issue https://github.com/comigor/artemis/issues/214
and we can return a map<String,String> from api manger and map in example

2020-09-29 14:05 UTC, MinaSamirCap commented on example/lib/apis/address_apis.dart
> +      5, 1, (AddressesModel addressPaginator) {}, (ApiErrorModel error) {});
AddressesWrapper

2020-09-29 14:05 UTC, MinaSamirCap commented on example/lib/apis/cart_api.dart
> +  await CartApiManager.cartDataApi(
cartApi

2020-09-29 14:05 UTC, MinaSamirCap commented on example/lib/apis/general_api.dart
> +      (SlidersModel sliderModel) {}, (ApiErrorModel error) {});
rename sliders model

2020-09-29 14:05 UTC, MinaSamirCap commented on example/lib/apis/general_api.dart
> +      (SlidersModel sliderModel) {}, (ApiErrorModel error) {});
SliderList

2020-09-29 14:05 UTC, MinaSamirCap commented on example/lib/main.dart
>    // TODO remove the base url from the main example. [May be not because the graphConfig file]
remove it

2020-09-29 14:05 UTC, MinaSamirCap commented on lib/common_models/common_models.dart
> +class UserProfileModel {
add wrapper and list models

2020-10-01 13:05 UTC, MinaSamirCap approved these changes

2020-10-01 13:07 UTC, merged